// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"meh/ent/follow"
	"meh/ent/meh"
	"meh/ent/schema"
	"meh/ent/timeline"
	"meh/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	followMixin := schema.Follow{}.Mixin()
	followMixinFields1 := followMixin[1].Fields()
	_ = followMixinFields1
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followMixinFields1[0].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	// followDescUpdatedAt is the schema descriptor for updated_at field.
	followDescUpdatedAt := followMixinFields1[1].Descriptor()
	// follow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	follow.DefaultUpdatedAt = followDescUpdatedAt.Default.(func() time.Time)
	mehMixin := schema.Meh{}.Mixin()
	mehMixinFields1 := mehMixin[1].Fields()
	_ = mehMixinFields1
	mehFields := schema.Meh{}.Fields()
	_ = mehFields
	// mehDescCreatedAt is the schema descriptor for created_at field.
	mehDescCreatedAt := mehMixinFields1[0].Descriptor()
	// meh.DefaultCreatedAt holds the default value on creation for the created_at field.
	meh.DefaultCreatedAt = mehDescCreatedAt.Default.(func() time.Time)
	// mehDescUpdatedAt is the schema descriptor for updated_at field.
	mehDescUpdatedAt := mehMixinFields1[1].Descriptor()
	// meh.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	meh.DefaultUpdatedAt = mehDescUpdatedAt.Default.(func() time.Time)
	// mehDescText is the schema descriptor for text field.
	mehDescText := mehFields[1].Descriptor()
	// meh.TextValidator is a validator for the "text" field. It is called by the builders before save.
	meh.TextValidator = mehDescText.Validators[0].(func(string) error)
	timelineMixin := schema.Timeline{}.Mixin()
	timelineMixinFields1 := timelineMixin[1].Fields()
	_ = timelineMixinFields1
	timelineFields := schema.Timeline{}.Fields()
	_ = timelineFields
	// timelineDescCreatedAt is the schema descriptor for created_at field.
	timelineDescCreatedAt := timelineMixinFields1[0].Descriptor()
	// timeline.DefaultCreatedAt holds the default value on creation for the created_at field.
	timeline.DefaultCreatedAt = timelineDescCreatedAt.Default.(func() time.Time)
	// timelineDescUpdatedAt is the schema descriptor for updated_at field.
	timelineDescUpdatedAt := timelineMixinFields1[1].Descriptor()
	// timeline.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timeline.DefaultUpdatedAt = timelineDescUpdatedAt.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
