// Code generated by entc, DO NOT EDIT.

package timeline

import (
	"time"
)

const (
	// Label holds the string label denoting the timeline type in the database.
	Label = "timeline"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMehID holds the string denoting the meh_id field in the database.
	FieldMehID = "meh_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeMeh holds the string denoting the meh edge name in mutations.
	EdgeMeh = "meh"
	// Table holds the table name of the timeline in the database.
	Table = "timelines"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "timelines"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// MehTable is the table that holds the meh relation/edge.
	MehTable = "timelines"
	// MehInverseTable is the table name for the Meh entity.
	// It exists in this package in order to avoid circular dependency with the "meh" package.
	MehInverseTable = "mehs"
	// MehColumn is the table column denoting the meh relation/edge.
	MehColumn = "meh_id"
)

// Columns holds all SQL columns for timeline fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldMehID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
