// Code generated by entc, DO NOT EDIT.

package follow

import (
	"time"
)

const (
	// Label holds the string label denoting the follow type in the database.
	Label = "follow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFolloweeID holds the string denoting the followee_id field in the database.
	FieldFolloweeID = "followee_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeFollowee holds the string denoting the followee edge name in mutations.
	EdgeFollowee = "followee"
	// Table holds the table name of the follow in the database.
	Table = "follows"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "follows"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// FolloweeTable is the table that holds the followee relation/edge.
	FolloweeTable = "follows"
	// FolloweeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	FolloweeInverseTable = "users"
	// FolloweeColumn is the table column denoting the followee relation/edge.
	FolloweeColumn = "followee_id"
)

// Columns holds all SQL columns for follow fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldFolloweeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
