openapi: 3.0.0
info:
  title: MEH API
  version: 1.0.0
servers:
  - url: https://api.example.com/
security:
- Bearer: []
paths:
  /users:
    post:
      operationId: createUser
      description: ユーザー登録をする
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - screen_name
              properties:
                screen_name:
                  type: string
                  description: スクリーンネーム
                  example: gami
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: "Resource not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: "BF-APIBearer is invalid"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /follows/create:
    post:
      operationId: followUser
      description: ユーザーをフォローする
      tags:
        - follow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - followee_id
              properties:
                user_id:
                  type: integer
                  format: uint64
                  description: フォローするユーザーのID
                  example: 999999
                followee_id:
                  type: integer
                  format: uint64
                  description: フォローされるユーザーのID
                  example: 999998
      responses:
        '201':
          description: "Created"
        '400':
          description: "Resource not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: "BF-APIBearer is invalid"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /follows/delete:
    post:
      operationId: removeUser
      description: フォローしたユーザーをリムーブする
      tags:
        - follow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - followee_id
              properties:
                user_id:
                  type: integer
                  format: uint64
                  description: フォローしているユーザーのID
                  example: 999999
                followee_id:
                  type: integer
                  format: uint64
                  description: フォローされているユーザーのID
                  example: 999998
      responses:
        '200':
          description: "OK"
        '400':
          description: "Resource not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: "BF-APIBearer is invalid"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /mehs:
    post:
      operationId: createMeh
      description: テキストを投稿する
      tags:
        - meh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - text
              properties:
                user_id:
                  type: integer
                  format: uint64
                  description: 投稿するユーザーのID
                  example: 999999
                text:
                  type: string
                  description: テキスト
                  example: "おなかすいた"
      responses:
        '201':
          description: "Created"
        '400':
          description: "Resource not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: "BF-APIBearer is invalid"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /me/timeline:
    get:  
      operationId: showTimeline
      description: タイムラインを表示する
      tags:
        - meh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - pagination
              properties:
                pagination:
                  $ref: '#/components/schemas/Pagination'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineResponse'
        '400':
          description: "Resource not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: "BF-APIBearer is invalid"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Unknown error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TimelineResponse:
      type: object
      required:
        - pagination
        - mehs
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        mehs:
          type: array
          items:
            $ref: '#/components/schemas/Meh'
    Pagination:
      type: object
      required:
        - count
      properties:
        last_id:
          type: integer
          format: uint64
          description: ページの最後の要素のID
          example: 999999
        count:
          type: integer
          format: uint64
          description: 1ページの最大数
          example: 100
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "something is bad"
    User:
      type: object
      required:
        - id
        - screen_name
      properties:
        id:
          type: integer
          format: uint64
          description: ユーザーID
          example: 999999
        screen_name:
          type: string
          description: 名前
          example: gami
    Meh:
      type: object
      required:
        - text
      properties:
        id:
          type: integer
          format: uint64
          description: ユーザーID
          example: 999999
        text:
          type: string
          description: 投稿したテキスト
          example: おなかすいた
        user:
          $ref: '#/components/schemas/User'
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      example: 1
