// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)

// Meh is the predicate function for meh builders.
type Meh func(*sql.Selector)

// Timeline is the predicate function for timeline builders.
type Timeline func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
